In [5]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.6 MB 3.3 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.6 MB 5.0 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.6 MB 5.3 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.6 MB 5.7 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.6 MB 6.3 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 6.6 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.6 MB 7.0 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 6.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 6.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np


In [7]:
arr=np.array([1,2,3,4,5])

In [8]:
print(arr)

[1 2 3 4 5]


In [9]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(arr.shape)

(5,)


In [12]:
print(arr1.shape)

(3, 3)


In [14]:
print(arr1.ndim)

2


In [15]:
print(arr.size)

5


In [16]:
a=np.zeros(3)
print(a)

[0. 0. 0.]


In [19]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
c=np.zeros(10,dtype=int)
print(c)

[0 0 0 0 0 0 0 0 0 0]


In [21]:
d=np.full((3,3),26122004)
print(d)

[[26122004 26122004 26122004]
 [26122004 26122004 26122004]
 [26122004 26122004 26122004]]


In [22]:
e=np.arange(1,20,2)
print(e)

[ 1  3  5  7  9 11 13 15 17 19]


In [36]:
d=np.random.randint(1,10,(3,3))
print(d)
print(d[:2,:3])
print(d[:1])

[[2 7 9]
 [2 1 4]
 [1 5 4]]
[[2 7 9]
 [2 1 4]]
[[2 7 9]]


In [33]:
x1=np.random.randint(10,size=6)
print(x1)
print(x1[-1])
print(x1.dtype)
print(x1[:4])

[5 6 6 8 8 4]
4
int32
[5 6 6 8]
